// Columns: Vietnamese, Turkish, French, Indonesian.
const extraLanguageRows = {
'nav.home':['Trang chủ','Ana sayfa','Accueil','Beranda'],
'nav.announcements':['Thông báo','Duyurular','Annonces','Pengumuman'],
'nav.kingdom':['Ban lãnh đạo','Liderlik','Direction','Kepemimpinan'],
'nav.migration':['Di cư','Göç','Migration','Migrasi'],
'nav.achievements':['Thành tích','Başarılar','Hauts faits','Prestasi'],
'nav.media':['Thư viện','Medya','Médias','Media'],
'nav.guides':['Hướng dẫn','Rehberler','Guides','Panduan'],
'nav.contacts':['Liên hệ','İletişim','Contact','Kontak'],
'layout.language':['Ngôn ngữ','Dil','Langue','Bahasa'],
'layout.homeAria':['Trang chủ bang hội','Lonca ana sayfası','Accueil de la guilde','Beranda guild'],
'layout.navAria':['Điều hướng chính','Ana gezinme','Navigation principale','Navigasi utama'],
'brand.subtitle':['Một bang hội. Một huyền thoại.','Tek lonca. Tek destan.','Une guilde. Une épopée.','Satu guild. Satu kisah.'],
'intro.tagline':['Mọi huyền thoại đều bắt đầu từ đây.','Her efsane burada başlar.','Toute légende commence ici.','Setiap legenda dimulai di sini.'],
'intro.languageQuestion':['Huyền thoại của bạn sẽ được kể bằng ngôn ngữ nào?','Destanın hangi dilde anlatılsın?','Dans quelle langue raconter votre épopée ?','Dalam bahasa apa kisahmu akan diceritakan?'],
'home.heroTitle':['Để quạ mang danh chúng ta đi xa.','Kuzgunlar adımızı taşısın.','Que les corbeaux portent notre nom.','Biarkan gagak membawa nama kita.'],
'home.heroText':['Từ vịnh hẹp đến tiền tuyến. GUL cùng chiến đấu, giữ vững trận địa và để lại dấu ấn.','Fiyortlardan cepheye. GUL birlikte savaşır, yerini korur ve iz bırakır.','Des fjords aux premières lignes, GUL combat ensemble, tient bon et laisse son empreinte.','Dari fjord hingga garis depan. GUL bertarung bersama, bertahan, dan meninggalkan jejak.'],
'home.sectionsEyebrow':['Bên kia cánh cổng','Kapıların ötesinde','Au-delà des portes','Di balik gerbang'],
'home.sectionsTitle':['Chọn hướng đi của bạn','Rotanı Seç','Choisissez votre cap','Tentukan Arahmu'],
'home.sectionsIntro':['Gia nhập hàng ngũ. Sống lại trận chiến. Tìm bước đi tiếp theo.','Saflara katıl. Savaşları yeniden yaşa. Sonraki adımını bul.','Rejoignez les rangs. Revivez les batailles. Préparez votre prochaine étape.','Bergabunglah. Kenang pertempuran. Temukan langkah berikutnya.'],
'home.footer':['GUL • Viking Rise','GUL • Viking Rise','GUL • Viking Rise','GUL • Viking Rise'],
'announcements.eyebrow':['Tin từ đại sảnh','Salondan haberler','Les nouvelles de la halle','Kabar dari aula'],
'announcements.title':['Chờ hiệu lệnh','İşareti Bekle','Guettez le signal','Nantikan Isyarat'],
'announcements.intro':['Sự kiện, lời nhắc và tin quan trọng cho bước đi tiếp theo của GUL.','Etkinlikler, hatırlatmalar ve önemli haberler. GUL’un sonraki hamlesi için gereken her şey.','Événements, rappels et nouvelles importantes pour la prochaine étape de GUL.','Acara, pengingat, dan kabar penting untuk langkah GUL berikutnya.'],
'announcements.events':['Sự kiện','Etkinlikler','Événements','Acara'],
'announcements.reminders':['Lời nhắc','Hatırlatmalar','Rappels','Pengingat'],
'announcements.updates':['Tin bang hội','Lonca Haberleri','Nouvelles de la guilde','Kabar Guild'],
'announcements.eventsDesc':['Tập kết, chiến tranh vương quốc và các cuộc gặp bang hội.','Toplanmalar, krallık savaşları ve lonca buluşmaları.','Rassemblements, batailles du royaume et rencontres de guilde.','Rally, pertempuran kerajaan, dan pertemuan guild.'],
'announcements.remindersDesc':['Thời gian và những chuẩn bị cần ghi nhớ.','Unutmaman gereken saatler ve hazırlıklar.','Les horaires et préparatifs à retenir.','Waktu dan persiapan yang perlu diingat.'],
'announcements.updatesDesc':['Tin quan trọng từ ban lãnh đạo GUL.','GUL liderliğinden önemli haberler.','Les nouvelles importantes de la direction de GUL.','Kabar penting dari pemimpin GUL.'],
'announcements.status':['Đang chờ tin mới','Yeni haber bekleniyor','En attente du prochain message','Menunggu kabar berikutnya'],
'announcements.waitTitle':['Hiệu lệnh tiếp theo sẽ vang lên tại đây.','Sonraki çağrı burada duyulacak.','Le prochain appel retentira ici.','Panggilan berikutnya akan terdengar di sini.'],
'announcements.waitText':['Thông báo mới sẽ sớm xuất hiện. Trong lúc chờ, hãy tham gia Discord của bang hội.','Yeni duyurular yakında burada. O zamana kadar loncamızın Discord’una katıl.','De nouvelles annonces arriveront bientôt. En attendant, retrouvez la guilde sur Discord.','Pengumuman baru segera hadir. Sementara itu, bergabunglah di Discord guild.'],
'announcements.discord':['Mở Discord','Discord’u Aç','Ouvrir Discord','Buka Discord'],
'announcements.footer':['Sự kiện và tin từ GUL','GUL etkinlikleri ve haberleri','Événements et nouvelles de GUL','Acara dan kabar GUL'],
'migration.eyebrow':['Hành trình đến GUL','GUL’a Yolculuğun','Votre passage vers GUL','Perjalananmu ke GUL'],
'migration.title':['Bến bờ mới. Đồng minh mạnh hơn.','Yeni Kıyılar. Daha Güçlü Müttefikler.','Nouveaux rivages. Alliés plus forts.','Pantai Baru. Sekutu Lebih Kuat.'],
'migration.intro':['Hướng đến GUL. Tìm hiểu yêu cầu và cho R4 biết bạn mang gì đến hàng ngũ.','Rotanı GUL’a çevir. Beklentilerimizi öğren ve R4’lerimize saflara ne katacağını anlat.','Mettez le cap sur GUL. Découvrez nos attentes et présentez votre candidature aux R4.','Arahkan perjalananmu ke GUL. Pelajari persyaratan dan ceritakan kontribusimu kepada R4.'],
'migration.requirementsTitle':['Trước khi ra khơi','Yelken Açmadan Önce','Avant de prendre le large','Sebelum Berlayar'],
'migration.reqPower':['Yêu cầu sức mạnh: hỏi R4 về ngưỡng hiện tại.','Güç şartı: güncel eşiği R4’lerimize sor.','Puissance requise : demandez le seuil actuel à nos R4.','Persyaratan kekuatan: tanyakan batas saat ini kepada R4.'],
'migration.reqActivity':['Cùng bang hội tham gia sự kiện và chiến tranh vương quốc.','Etkinliklerde ve krallık savaşlarında loncanın yanında ol.','Participez aux événements et aux guerres du royaume avec la guilde.','Ikut bersama guild dalam acara dan perang kerajaan.'],
'migration.reqContact':['Giữ liên lạc qua Discord hoặc kênh chính của bang hội.','Discord veya ana lonca kanalımız üzerinden iletişimde kal.','Restez en contact sur Discord ou notre canal principal.','Tetap terhubung melalui Discord atau kanal utama guild.'],
'migration.reqRecord':['Lý lịch trong sạch: không phản bội, quấy rối hoặc cố ý gây rối ở vương quốc trước.','Önceki krallığında ihanet, taciz veya kasıtlı huzursuzluk geçmişin olmamalı.','Un passé sans trahison, harcèlement ni perturbation volontaire dans votre ancien royaume.','Rekam jejak baik: tanpa pengkhianatan, pelecehan, atau gangguan disengaja di kerajaan sebelumnya.'],
'migration.formTitle':['Tìm vị trí của bạn','Yerini Al','Prenez votre place','Raih Tempatmu'],
'migration.nickname':['Tên trong game','Oyun içi ad','Pseudo en jeu','Nama dalam game'],
'migration.playerId':['ID người chơi','Oyuncu ID','Identifiant joueur','ID pemain'],
'migration.power':['Sức mạnh hiện tại','Mevcut güç','Puissance actuelle','Kekuatan saat ini'],
'migration.comment':['Bạn mang gì đến GUL?','GUL’a ne katacaksın?','Que pouvez-vous apporter à GUL ?','Apa kontribusimu untuk GUL?'],
'migration.submit':['Đăng ký gia nhập GUL','GUL’a Katılmak İçin Başvur','Postuler chez GUL','Daftar ke GUL'],
'migration.nicknamePlaceholder':['Ví dụ: Ragnar','Örnek: Ragnar','Exemple : Ragnar','Contoh: Ragnar'],
'migration.playerIdPlaceholder':['ID của bạn','ID’n','Votre identifiant','ID kamu'],
'migration.powerPlaceholder':['Ví dụ: 45M','Örnek: 45M','Exemple : 45M','Contoh: 45M'],
'migration.commentPlaceholder':['Kinh nghiệm, múi giờ và lý do muốn gia nhập GUL','Deneyimin, saat dilimin ve GUL’a katılma nedenin','Votre expérience, fuseau horaire et motivation','Pengalaman, zona waktu, dan alasan bergabung'],
'migration.footer':['R4 sẽ xét duyệt đơn','Başvuruları R4’ler inceler','Candidatures examinées par les R4','Pendaftaran ditinjau oleh R4'],
'achievements.eyebrow':['Đại sảnh vinh danh','Şöhret Salonu','Panthéon','Aula Kehormatan'],
'achievements.title':['Vinh quang giành được','Zor Kazanılan Zafer','La gloire se mérite','Kejayaan yang Diraih'],
'achievements.intro':['Huy hiệu, thứ hạng và cột mốc. Vinh dự của GUL sẽ được ghi lại tại đây.','Kazanılan rozetler, yükselen sıralamalar, aşılan dönüm noktaları. GUL’un onurları burada.','Insignes, classements et étapes franchies : les honneurs de GUL seront réunis ici.','Lencana, peringkat, dan pencapaian. Kehormatan GUL akan tercatat di sini.'],
'achievements.waitLabel':['Biên niên sử đang thành hình','Tarihçe şekilleniyor','La chronique prend forme','Catatan sejarah mulai terbentuk'],
'achievements.waitTitle':['Chiến thắng tiếp theo thuộc về nơi này.','Sonraki zaferin yeri burası.','Le prochain triomphe trouvera sa place ici.','Kemenangan berikutnya akan hadir di sini.'],
'achievements.waitText':['Huy hiệu bang hội, thứ hạng sự kiện và các cột mốc sẽ sớm được trưng bày.','Lonca rozetleri, etkinlik sıralamaları ve başarılarımız yakında burada sergilenecek.','Insignes de guilde, classements et grandes étapes seront bientôt présentés ici.','Lencana guild, peringkat acara, dan pencapaian akan segera ditampilkan.'],
'achievements.waitReturn':['Hãy quay lại sớm. Vinh quang đáng để chờ.','Yakında dön. Zafer beklemeye değer.','Revenez bientôt. La gloire mérite l’attente.','Kembali segera. Kejayaan layak dinantikan.'],
'achievements.footer':['Biên niên sử chiến thắng','Zaferlerin tarihçesi','Chronique des victoires','Catatan kemenangan'],
'media.eyebrow':['Phía sau lá cờ','Sancağın Ardında','Derrière la bannière','Di Balik Panji'],
'media.title':['Qua lửa và vịnh hẹp','Ateş ve Fiyortlar','Entre feu et fjords','Melalui Api dan Fjord'],
'media.intro':['Thế giới qua góc nhìn những người cùng ra khơi và chiến đấu.','Birlikte yelken açıp savaşanların gözünden dünyamız.','Notre monde, vu par ceux qui naviguent et combattent ensemble.','Dunia kita dari sudut pandang mereka yang berlayar dan bertarung bersama.'],
'media.waitLabel':['GUL qua ống kính','GUL Odakta','GUL en images','GUL dalam Sorotan'],
'media.waitTitle':['Có những khoảnh khắc đáng được nhìn thấy.','Bazı anlar görülmeye değer.','Certains instants méritent d’être vus.','Beberapa momen layak disaksikan.'],
'media.waitText':['Chúng tôi đang thu thập hình ảnh từ các chuyến đi, trận chiến và đời sống bang hội. Ảnh và video sẽ sớm có mặt.','Seferlerimizden, savaşlarımızdan ve lonca yaşamından görüntüler topluyoruz. Fotoğraf ve videolar yakında burada.','Nous rassemblons les images de nos voyages, batailles et moments de guilde. Photos et vidéos arrivent bientôt.','Kami mengumpulkan momen perjalanan, pertempuran, dan kehidupan guild. Foto dan video segera hadir.'],
'media.waitReturn':['Những hình ảnh đầu tiên đang đến gần.','İlk görüntüler ufukta.','Les premières images se profilent à l’horizon.','Cuplikan pertama sudah di cakrawala.'],
'media.footer':['Thư viện đang thành hình','Galeri şekilleniyor','La galerie prend forme','Galeri sedang disiapkan'],
'guides.eyebrow':['Hướng dẫn toàn diện GUL','GUL Kapsamlı Rehber','Guide complet GUL','Panduan Lengkap GUL'],
'guides.title':['Hướng dẫn Viking Rise','Viking Rise Rehberleri','Guides Viking Rise','Panduan Viking Rise'],
'guides.intro':['Chọn chủ đề để tìm lời khuyên về chiến đấu, đội hình và phát triển. Bảng gốc và công cụ PvP luôn sẵn có.','Savaş, dizilim ve gelişim için bir konu seç. Orijinal tablo ve PvP hesaplayıcısı elinin altında.','Choisissez un sujet : combats, compositions et progression. Gardez le tableau original et le calculateur PvP à portée de main.','Pilih topik untuk kiat pertempuran, susunan, dan perkembangan. Tabel asli dan kalkulator PvP selalu tersedia.'],
'guides.download':['Mở Google Sheets','Google Tablosunu Aç','Ouvrir Google Sheets','Buka Google Sheets'],
'guides.calculator':['Công cụ tính PvP','PvP hesaplayıcısı','Calculateur PvP','Kalkulator PvP'],
'guides.credit':['Nguồn: GUL Ultimate Guide. Tác giả: Thorbjørnsson.','Kaynak: GUL Ultimate Guide. Hazırlayan: Thorbjørnsson.','Source : GUL Ultimate Guide. Crédits : Thorbjørnsson.','Sumber: GUL Ultimate Guide. Kredit: Thorbjørnsson.'],
'kingdom.eyebrow':['Người cầm lái','Dümenin Başında','À la barre','Di Kemudi'],
'kingdom.title':['Đại sảnh GUL','GUL Salonu','La halle de GUL','Aula GUL'],
'kingdom.intro':['Ban lãnh đạo bang hội: thủ lĩnh R5 và các R4.','Lonca liderlik kadrosu: R5 lideri ve R4’ler.','Direction de la guilde : chef R5 et officiers R4.','Jajaran pemimpin guild: pemimpin R5 dan R4.'],
'kingdom.leaderEyebrow':['Thủ lĩnh bang hội','Lonca Lideri','Chef de guilde','Pemimpin Guild'],
'kingdom.leaderContact':['Nhắn tin cho thủ lĩnh','Lidere Mesaj Gönder','Contacter le chef','Hubungi Pemimpin'],
'kingdom.leaderText':['Dẫn dắt GUL. Xây dựng liên minh, chỉ huy chiến đấu và định hướng cho vương quốc.','GUL’un dümeninde. İttifaklar kurar, hücuma önderlik eder ve krallığın rotasını belirler.','À la tête de GUL : bâtir des alliances, mener la charge et fixer le cap du royaume.','Memimpin GUL. Membangun aliansi, memimpin serangan, dan menentukan arah kerajaan.'],
'kingdom.officersEyebrow':['Đội ngũ R4','R4 Kadrosu','Officiers','Jajaran R4'],
'kingdom.officersTitle':['Danh sách R4','R4 Kadrosu','Les R4','Daftar R4'],
'kingdom.contactTitle':['Cách liên hệ','Nasıl İletişim Kurulur','Comment nous contacter','Cara Menghubungi'],
'kingdom.contactText':['Việc khẩn cấp: nhắn R5 hoặc R4 đang có mặt. Với di cư, ngoại giao hoặc tranh chấp, hãy gửi tên, tọa độ và mô tả ngắn.','Acil konularda R5’e veya müsait bir R4’e yaz. Göç, diplomasi ve anlaşmazlıklarda adını, koordinatlarını ve kısa açıklamanı ekle.','En cas d’urgence, contactez le R5 ou un R4 disponible. Pour la migration, la diplomatie ou un différend, indiquez votre pseudo, vos coordonnées et un bref résumé.','Untuk urusan mendesak, hubungi R5 atau R4 yang tersedia. Untuk migrasi, diplomasi, atau perselisihan, sertakan nama, koordinat, dan penjelasan singkat.'],
'kingdom.footer':['Trật tự trong vương quốc','Krallıkta düzen','L’ordre du royaume','Tatanan kerajaan'],
'contacts.eyebrow':['Kết nối GUL','GUL’a Ulaş','Joindre GUL','Hubungi GUL'],
'contacts.title':['Gửi cánh quạ','Bir Kuzgun Gönder','Envoyez un corbeau','Kirim Seekor Gagak'],
'contacts.intro':['Tìm đồng đội, liên hệ thủ lĩnh hoặc chuẩn bị cho chiến dịch tiếp theo.','Ekibini bul, lidere ulaş veya sonraki sefere hazırlan.','Retrouvez votre équipage, contactez le chef ou préparez la prochaine campagne.','Temukan timmu, hubungi pemimpin, atau siapkan kampanye berikutnya.'],
'contacts.discordTitle':['Đại sảnh bang hội','Lonca Salonu','La halle de la guilde','Aula Guild'],
'contacts.discordText':['Tham gia GUL trên Discord. Gặp đồng đội và giữ liên lạc với bang hội.','Discord’da GUL’a katıl. Ekiple tanış ve loncayla bağlantıda kal.','Rejoignez GUL sur Discord. Rencontrez l’équipage et gardez le contact.','Bergabung dengan GUL di Discord. Kenali tim dan tetap terhubung.'],
'contacts.discordLink':['Tham gia Discord','Discord’umuza Katıl','Rejoindre notre Discord','Gabung Discord'],
'contacts.leadersTitle':['Trao đổi với thủ lĩnh','Liderle Bir Görüşme','Un mot avec le chef','Berbicara dengan Pemimpin'],
'contacts.leadersText':['Về di cư, liên minh hoặc bang hội, nhắn The Punisher trên Telegram.','Göç, ittifak veya lonca soruları için Telegram’da The Punisher’a yaz.','Pour la migration, les alliances ou la guilde, contactez The Punisher sur Telegram.','Untuk migrasi, aliansi, atau pertanyaan guild, hubungi The Punisher di Telegram.'],
'contacts.leadersLink':['Nhắn trên Telegram','Telegram’da Mesaj Gönder','Écrire sur Telegram','Kirim Pesan di Telegram'],
'contacts.resourcesTitle':['Bàn chiến thuật','Savaş Masası','La table de guerre','Meja Perang'],
'contacts.resourcesText':['Hướng dẫn, đội hình và công cụ tính để chuẩn bị chiến đấu.','Savaşa hazırlanmak için rehberler, dizilimler ve hesaplayıcılar.','Guides, compositions et calculateurs pour préparer les batailles.','Panduan, susunan, dan kalkulator untuk persiapan pertempuran.'],
'contacts.resourcesLink':['Khám phá hướng dẫn','Rehberleri Keşfet','Explorer les guides','Jelajahi Panduan'],
'contacts.footer':['Liên hệ dễ dàng','Kolay iletişim','Le contact à portée de main','Kontak yang mudah']
};
window.GUL_EXTRA_LANGUAGES = Object.fromEntries(['vi','tr','fr','id'].map((lang,index)=>[lang,Object.fromEntries(Object.entries(extraLanguageRows).map(([key,values])=>[key,values[index]]))]));
window.GUL_GUIDE_LABELS = {
 'Start Here':['Bắt đầu tại đây','Buradan Başla','Commencez ici','Mulai di Sini'],
 'Battle & Builds':['Chiến đấu & đội hình','Savaş ve Dizilimler','Combats et compositions','Pertempuran & Susunan'],
 'Mounts & Equipment':['Thú cưỡi & trang bị','Binekler ve Ekipman','Montures et équipement','Tunggangan & Perlengkapan'],
 'Growth & Resources':['Phát triển & tài nguyên','Gelişim ve Kaynaklar','Progression et ressources','Perkembangan & Sumber Daya'],
 'Events & Packs':['Sự kiện & gói','Etkinlikler ve Paketler','Événements et packs','Acara & Paket'],
 'Skill Libraries':['Thư viện kỹ năng','Beceri Kütüphaneleri','Bibliothèques de compétences','Pustaka Keahlian'],
 'PvP Tactics':['Chiến thuật PvP','PvP Taktikleri','Tactiques PvP','Taktik PvP'],
 'Defending an Attack':['Phòng thủ','Saldırı Savunması','Défendre une attaque','Bertahan dari Serangan'],
 'Healing & Training':['Chữa trị & huấn luyện','İyileştirme ve Eğitim','Soins et entraînement','Penyembuhan & Pelatihan'],
 'Mounts':['Thú cưỡi','Binekler','Montures','Tunggangan'],
 'Mount Skills':['Kỹ năng thú cưỡi','Binek Becerileri','Compétences de monture','Keahlian Tunggangan'],
 'Monster Gear':['Trang bị diệt quái','Canavar Ekipmanı','Équipement contre les monstres','Perlengkapan Monster'],
 'Blessed Gear':['Trang bị ban phước','Kutsanmış Ekipman','Équipement béni','Perlengkapan Berkat'],
 'Packs':['Gói','Paketler','Packs','Paket'],
 'Skill Experience':['Kinh nghiệm kỹ năng','Beceri Deneyimi','Expérience des compétences','Pengalaman Keahlian'],
 'Hero Experience':['Kinh nghiệm anh hùng','Kahraman Deneyimi','Expérience des héros','Pengalaman Hero'],
 'Hero Fragments':['Mảnh anh hùng','Kahraman Parçaları','Fragments de héros','Fragmen Hero'],
 'Talents':['Thiên phú','Yetenekler','Talents','Talenta'],
 'Research Costs':['Chi phí nghiên cứu','Araştırma Maliyetleri','Coûts de recherche','Biaya Riset'],
 'Legendary Skills':['Kỹ năng huyền thoại','Efsanevi Beceriler','Compétences légendaires','Keahlian Legendaris'],
 'Purple Skills':['Kỹ năng tím','Mor Beceriler','Compétences violettes','Keahlian Ungu'],
 'Mount Skill Library':['Thư viện kỹ năng thú cưỡi','Binek Beceri Kütüphanesi','Bibliothèque des compétences de monture','Pustaka Keahlian Tunggangan'],
 'FAQ':['Câu hỏi thường gặp','Sık Sorulan Sorular','Questions fréquentes','Pertanyaan Umum']
};
for (let season=2;season<=5;season++) window.GUL_GUIDE_LABELS['Season '+season+' Builds']=['Đội hình mùa '+season,'Sezon '+season+' Dizilimleri','Compositions de saison '+season,'Susunan Musim '+season];
